{
  "uid" : "2fdd1377d1379b16",
  "name" : "测试密码输入错误的场景",
  "fullName" : "testcases.test_my_interface01.test_login.TestLogin#test_login",
  "historyId" : "6a1b7213a76d4bf7465f276e4e463fdc",
  "time" : {
    "start" : 1646221621653,
    "stop" : 1646221621692,
    "duration" : 39
  },
  "description" : "京东小程序入口登入接口",
  "descriptionHtml" : "<p>京东小程序入口登入接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 11,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "京东小程序入口登入接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "3f7956d269cbd5aa",
      "name" : "接口路径",
      "source" : "3f7956d269cbd5aa.attach",
      "type" : "text/plain",
      "size" : 32
    }, {
      "uid" : "8dac3bd3858c98c",
      "name" : "接口参数",
      "source" : "8dac3bd3858c98c.attach",
      "type" : "text/plain",
      "size" : 47
    }, {
      "uid" : "66e236f46453ba80",
      "name" : "响应结果",
      "source" : "66e236f46453ba80.attach",
      "type" : "text/plain",
      "size" : 49
    }, {
      "uid" : "3018d6c558684469",
      "name" : "log",
      "source" : "3018d6c558684469.txt",
      "type" : "text/plain",
      "size" : 326
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "登入模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F0ACF8>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "19951a4ee399e110",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000155228EED30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221549620,
        "stop" : 1646221551650,
        "duration" : 2030
      }
    }, {
      "uid" : "43c539aa0d4d4613",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0FD6A860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221493330,
        "stop" : 1646221495352,
        "duration" : 2022
      }
    }, {
      "uid" : "2c9c4274467d3e7d",
      "status" : "passed",
      "time" : {
        "start" : 1646199360854,
        "stop" : 1646199360884,
        "duration" : 30
      }
    }, {
      "uid" : "227db317720e9f94",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309110,
        "stop" : 1646199309126,
        "duration" : 16
      }
    }, {
      "uid" : "e6e9a7faf9827831",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199216806,
        "stop" : 1646199216824,
        "duration" : 18
      }
    }, {
      "uid" : "3a88b35c7361365b",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158613,
        "stop" : 1646199158632,
        "duration" : 19
      }
    }, {
      "uid" : "2da488958d65f539",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939520,
        "stop" : 1646198939537,
        "duration" : 17
      }
    }, {
      "uid" : "ded5c69989c98b1b",
      "status" : "passed",
      "time" : {
        "start" : 1646198590814,
        "stop" : 1646198590844,
        "duration" : 30
      }
    }, {
      "uid" : "1795686094ff1ea6",
      "status" : "passed",
      "time" : {
        "start" : 1646198233719,
        "stop" : 1646198233748,
        "duration" : 29
      }
    }, {
      "uid" : "cfd8b544a52a3010",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019599,
        "stop" : 1646198019608,
        "duration" : 9
      }
    }, {
      "uid" : "e6b065f09681dea5",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200801C59E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197960810,
        "stop" : 1646197962838,
        "duration" : 2028
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "2fdd1377d1379b16.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F0ACF8>" ]
}