{
  "uid" : "444445d60224bfe1",
  "name" : "测试密码为空的场景",
  "fullName" : "testcases.test_my_interface01.test_login.TestLogin#test_login",
  "historyId" : "fbdea112898d94c8c47131140044ea5c",
  "time" : {
    "start" : 1646221621695,
    "stop" : 1646221621729,
    "duration" : 34
  },
  "description" : "京东小程序入口登入接口",
  "descriptionHtml" : "<p>京东小程序入口登入接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 11,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "京东小程序入口登入接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "2c53fbfa1ceede62",
      "name" : "接口路径",
      "source" : "2c53fbfa1ceede62.attach",
      "type" : "text/plain",
      "size" : 32
    }, {
      "uid" : "756acc5745620317",
      "name" : "接口参数",
      "source" : "756acc5745620317.attach",
      "type" : "text/plain",
      "size" : 39
    }, {
      "uid" : "121b5d8a07b6c0df",
      "name" : "响应结果",
      "source" : "121b5d8a07b6c0df.attach",
      "type" : "text/plain",
      "size" : 43
    }, {
      "uid" : "a910c34725f59558",
      "name" : "log",
      "source" : "a910c34725f59558.txt",
      "type" : "text/plain",
      "size" : 320
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "登入模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F0ADD8>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "b56723d809e40515",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522A5D278>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221551832,
        "stop" : 1646221553863,
        "duration" : 2031
      }
    }, {
      "uid" : "d2892a5b568e2da2",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0FD3F0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221495513,
        "stop" : 1646221497562,
        "duration" : 2049
      }
    }, {
      "uid" : "3b09f8cdeca3caa",
      "status" : "passed",
      "time" : {
        "start" : 1646199360887,
        "stop" : 1646199360913,
        "duration" : 26
      }
    }, {
      "uid" : "b0773950ff925e6b",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309192,
        "stop" : 1646199309205,
        "duration" : 13
      }
    }, {
      "uid" : "cdf7946d245a10a4",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199216890,
        "stop" : 1646199216904,
        "duration" : 14
      }
    }, {
      "uid" : "af41545f5b556f8e",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158705,
        "stop" : 1646199158720,
        "duration" : 15
      }
    }, {
      "uid" : "7664eb2b020bcedf",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939601,
        "stop" : 1646198939615,
        "duration" : 14
      }
    }, {
      "uid" : "55c43597ed40bfb6",
      "status" : "passed",
      "time" : {
        "start" : 1646198590847,
        "stop" : 1646198590873,
        "duration" : 26
      }
    }, {
      "uid" : "39a69c8aee94f5c6",
      "status" : "passed",
      "time" : {
        "start" : 1646198233751,
        "stop" : 1646198233778,
        "duration" : 27
      }
    }, {
      "uid" : "ff7f8074072817bb",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019663,
        "stop" : 1646198019668,
        "duration" : 5
      }
    }, {
      "uid" : "85ba3dc14a4a4f3d",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200801F4358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197963015,
        "stop" : 1646197965043,
        "duration" : 2028
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "444445d60224bfe1.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F0ADD8>" ]
}