{
  "uid" : "87a025d85f14a7c2",
  "name" : "测试用户名为空的场景",
  "fullName" : "testcases.test_my_interface01.test_login.TestLogin#test_login",
  "historyId" : "1bb55d4815038396707b989bca08a201",
  "time" : {
    "start" : 1646221621615,
    "stop" : 1646221621650,
    "duration" : 35
  },
  "description" : "京东小程序入口登入接口",
  "descriptionHtml" : "<p>京东小程序入口登入接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 12,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "京东小程序入口登入接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "a5e8dd38d4803296",
      "name" : "接口路径",
      "source" : "a5e8dd38d4803296.attach",
      "type" : "text/plain",
      "size" : 32
    }, {
      "uid" : "dcf7326131b8ae09",
      "name" : "接口参数",
      "source" : "dcf7326131b8ae09.attach",
      "type" : "text/plain",
      "size" : 39
    }, {
      "uid" : "1bbb49f9f90aa4a9",
      "name" : "响应结果",
      "source" : "1bbb49f9f90aa4a9.attach",
      "type" : "text/plain",
      "size" : 46
    }, {
      "uid" : "a37ed587f122d4a2",
      "name" : "log",
      "source" : "a37ed587f122d4a2.txt",
      "type" : "text/plain",
      "size" : 323
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "登入模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F0AA58>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "5b550be824a4c9c2",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C0ABC62940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221595790,
        "stop" : 1646221597819,
        "duration" : 2029
      }
    }, {
      "uid" : "12e1ba3e420905f4",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522A0B400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221547425,
        "stop" : 1646221549450,
        "duration" : 2025
      }
    }, {
      "uid" : "ae064faea06d2e28",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0FB82A58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221491110,
        "stop" : 1646221493136,
        "duration" : 2026
      }
    }, {
      "uid" : "1ecfaee7f8b84d7e",
      "status" : "passed",
      "time" : {
        "start" : 1646199360824,
        "stop" : 1646199360851,
        "duration" : 27
      }
    }, {
      "uid" : "298e4becfabda292",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309005,
        "stop" : 1646199309042,
        "duration" : 37
      }
    }, {
      "uid" : "324cdb3a54088350",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199216736,
        "stop" : 1646199216750,
        "duration" : 14
      }
    }, {
      "uid" : "8f5fe34d9e3b3041",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158538,
        "stop" : 1646199158555,
        "duration" : 17
      }
    }, {
      "uid" : "62dd64db56627be6",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939448,
        "stop" : 1646198939463,
        "duration" : 15
      }
    }, {
      "uid" : "ed3034442dc6ce66",
      "status" : "passed",
      "time" : {
        "start" : 1646198590785,
        "stop" : 1646198590811,
        "duration" : 26
      }
    }, {
      "uid" : "ab242ebdf8ce3883",
      "status" : "passed",
      "time" : {
        "start" : 1646198233689,
        "stop" : 1646198233715,
        "duration" : 26
      }
    }, {
      "uid" : "7aea62326afbe6a9",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019536,
        "stop" : 1646198019543,
        "duration" : 7
      }
    }, {
      "uid" : "d16c2c641f4c4671",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200801999E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197958576,
        "stop" : 1646197960616,
        "duration" : 2040
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "87a025d85f14a7c2.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F0AA58>" ]
}