{
  "uid" : "ad33f435b3b9aa5d",
  "name" : "正常流程",
  "fullName" : "testcases.test_my_interface01.test_register.TestRegister#test_register",
  "historyId" : "e25f4ebc84105571575f4fb60c64503c",
  "time" : {
    "start" : 1646221621735,
    "stop" : 1646221621775,
    "duration" : 40
  },
  "description" : "京东小程序入口注册接口",
  "descriptionHtml" : "<p>京东小程序入口注册接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 11,
  "retriesStatusChange" : true,
  "beforeStages" : [ {
    "name" : "connect_db",
    "time" : {
      "start" : 1646221621732,
      "stop" : 1646221621734,
      "duration" : 2
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "description" : "京东小程序入口注册接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ff6a9a2d642f62e9",
      "name" : "接口路径",
      "source" : "ff6a9a2d642f62e9.attach",
      "type" : "text/plain",
      "size" : 30
    }, {
      "uid" : "e2487306a05436df",
      "name" : "接口参数",
      "source" : "e2487306a05436df.attach",
      "type" : "text/plain",
      "size" : 115
    }, {
      "uid" : "dc1a16c55f23c56f",
      "name" : "响应结果",
      "source" : "dc1a16c55f23c56f.attach",
      "type" : "text/plain",
      "size" : 37
    }, {
      "uid" : "5298e48d5c377363",
      "name" : "log",
      "source" : "5298e48d5c377363.txt",
      "type" : "text/plain",
      "size" : 306
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ {
    "name" : "connect_db::0",
    "time" : {
      "start" : 1646221621776,
      "stop" : 1646221621776,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "注册模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_register"
  }, {
    "name" : "subSuite",
    "value" : "TestRegister"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_register"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F38EF0>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "edfeb96ae18f56a2",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522A52160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221554051,
        "stop" : 1646221556079,
        "duration" : 2028
      }
    }, {
      "uid" : "c8d021190209a8dd",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0F8594E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221497749,
        "stop" : 1646221499779,
        "duration" : 2030
      }
    }, {
      "uid" : "c3e3c42d2ab0c299",
      "status" : "passed",
      "time" : {
        "start" : 1646199360919,
        "stop" : 1646199360956,
        "duration" : 37
      }
    }, {
      "uid" : "f138f9760a9bef48",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309264,
        "stop" : 1646199309284,
        "duration" : 20
      }
    }, {
      "uid" : "970640d2180ad878",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199216961,
        "stop" : 1646199216981,
        "duration" : 20
      }
    }, {
      "uid" : "f80979c7b0969457",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158781,
        "stop" : 1646199158805,
        "duration" : 24
      }
    }, {
      "uid" : "287b3c125c67af47",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939691,
        "stop" : 1646198939712,
        "duration" : 21
      }
    }, {
      "uid" : "80c551419899d214",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198590879,
        "stop" : 1646198590890,
        "duration" : 11
      }
    }, {
      "uid" : "11925c32ac584fd4",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198233784,
        "stop" : 1646198233797,
        "duration" : 13
      }
    }, {
      "uid" : "691aa190676e5042",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019735,
        "stop" : 1646198019749,
        "duration" : 14
      }
    }, {
      "uid" : "b490b2bf8cc12171",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200801C47F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197965235,
        "stop" : 1646197967282,
        "duration" : 2047
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "ad33f435b3b9aa5d.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F38EF0>" ]
}