{
  "uid" : "e8baf75ee769c8cb",
  "name" : "测试用户名输出错误的场景",
  "fullName" : "testcases.test_my_interface01.test_login.TestLogin#test_login",
  "historyId" : "aeed68005321ff57e803adc325a313ef",
  "time" : {
    "start" : 1646221621576,
    "stop" : 1646221621612,
    "duration" : 36
  },
  "description" : "京东小程序入口登入接口",
  "descriptionHtml" : "<p>京东小程序入口登入接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 12,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "京东小程序入口登入接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "15685eb5be3d5b5e",
      "name" : "接口路径",
      "source" : "15685eb5be3d5b5e.attach",
      "type" : "text/plain",
      "size" : 32
    }, {
      "uid" : "746a091c0052578d",
      "name" : "接口参数",
      "source" : "746a091c0052578d.attach",
      "type" : "text/plain",
      "size" : 48
    }, {
      "uid" : "b8c96e0b9f9bd079",
      "name" : "响应结果",
      "source" : "b8c96e0b9f9bd079.attach",
      "type" : "text/plain",
      "size" : 49
    }, {
      "uid" : "9f8e3240a44ce069",
      "name" : "log",
      "source" : "9f8e3240a44ce069.txt",
      "type" : "text/plain",
      "size" : 329
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "登入模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F0A940>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "91c1687873412362",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C0ABDC9630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221593581,
        "stop" : 1646221595615,
        "duration" : 2034
      }
    }, {
      "uid" : "824f9b169817adbb",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522935438>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221545209,
        "stop" : 1646221547244,
        "duration" : 2035
      }
    }, {
      "uid" : "77566d62ec19d996",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0FBBD0F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221488895,
        "stop" : 1646221490924,
        "duration" : 2029
      }
    }, {
      "uid" : "26da159edeaef2f",
      "status" : "passed",
      "time" : {
        "start" : 1646199360786,
        "stop" : 1646199360821,
        "duration" : 35
      }
    }, {
      "uid" : "5714dcb1491ada01",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199308926,
        "stop" : 1646199308944,
        "duration" : 18
      }
    }, {
      "uid" : "67bc5466767782af",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199216663,
        "stop" : 1646199216680,
        "duration" : 17
      }
    }, {
      "uid" : "85a43b1dad221e85",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158461,
        "stop" : 1646199158480,
        "duration" : 19
      }
    }, {
      "uid" : "ab5f9a74b1d5b184",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939375,
        "stop" : 1646198939393,
        "duration" : 18
      }
    }, {
      "uid" : "96428bf449936bab",
      "status" : "passed",
      "time" : {
        "start" : 1646198590747,
        "stop" : 1646198590781,
        "duration" : 34
      }
    }, {
      "uid" : "aca017b62d87bddf",
      "status" : "passed",
      "time" : {
        "start" : 1646198233651,
        "stop" : 1646198233686,
        "duration" : 35
      }
    }, {
      "uid" : "ff79e519b0b62a15",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019461,
        "stop" : 1646198019470,
        "duration" : 9
      }
    }, {
      "uid" : "967a3912483041cc",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002008023F9E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197956352,
        "stop" : 1646197958392,
        "duration" : 2040
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "e8baf75ee769c8cb.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F0A940>" ]
}